force-app/main/default/objects/Enrollment_Merge_Integration__e/Enrollment_Merge_Integration__e.object-meta.xml
<CustomObject>
    <description>Platform event for enrollment merge integration</description>
    <label>Enrollment Merge Integration</label>
    <pluralLabel>Enrollment Merge Integrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Enrollment_Merge_Integration__e/fields/MergeEnrollmentBody__c.field-meta.xml
<CustomField>
    <fullName>MergeEnrollmentBody__c</fullName>
    <label>MergeEnrollmentBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EnrollmentMergeIntEventTriggerTest.cls
@isTest
private class EnrollmentMergeIntEventTriggerTest {
    @isTest 
    static void testEnrollmentMergeIntEventTrigger() {
        //test data
        Enrollment_Merge_Integration__e testEvent = new Enrollment_Merge_Integration__e(
            MergeEnrollmentBody__c = 'test body'
        );

        // Test trigger
        Test.startTest();
        EventBus.publish(testEvent);
        Test.stopTest();

        
        System.assert(Test.isRunningTest(), 'Test is running');
        
    }
}